<div id="min_max_div" class="min_max_window div_elements_layout">
	<div id="arrow_up" class="arrow_up"></div>
	<div id="arrow_down" class="arrow_down"></div>
	<div id="temp_diff_max" class="max_value "><?php echo $this->maxValue;?></div>
	<div id="temp_diff_min" class="min_value "><?php echo $this->minValue;?></div>
</div>
<div id="temp_diff_current_value" class="div_value div_elements_layout"><?php echo $this->currValue;?></div>
<div class="footer-title">T verschil OK &amp; plenum</div>