<div id="min_max_div" class="min_max_window div_elements_layout">
	<div id="arrow_up" class="arrow_up"></div>
	<div id="arrow_down" class="arrow_down"></div>
	<div id="airspeed_max" class="max_value ">.30</div>
	<div id="airspeed_min" class="min_value ">.27</div>
</div>
<div id="airspeed_current_value" class="div_value div_elements_layout">?</div>
<div class="footer-title">Luchtsnelh. OK plenum</div>