<div id="min_max_div" class="min_max_window div_elements_layout">
	<div id="arrow_up" class="arrow_up"></div>
	<div id="arrow_down" class="arrow_down"></div>
	<div id="pres_diff_wash_max" class="max_value ">30</div>
	<div id="pres_diff_wash_min" class="min_value ">5</div>
</div>
<div id="pres_diff_wash_current_value" class="div_value div_elements_layout">?</div>
<div class="footer-title">Drukv. OK->wasruimte</div>