<div id="min_max_div" class="min_max_window div_elements_layout">
	<div id="arrow_up" class="arrow_up"></div>
	<div id="arrow_down" class="arrow_down"></div>
	<div id="ab_time_max" class="max_value "><?php echo $this->maxValue;?></div>
	<div id="ab_time_min" class="min_value "><?php echo $this->minValue;?></div>
</div>
<div id="ab_time_current_value" class="div_value_wide div_elements_layout" ><?php echo $this->currValue;?></div>
<div class="footer-title">Aantal minuten na toedienen antibiotica</div>