<div id="min_max_div" class="min_max_window div_elements_layout">
	<div id="arrow_up" class="arrow_up"></div>
	<div id="arrow_down" class="arrow_down"></div>
	<div id="temp_return_max" class="max_value ">24</div>
	<div id="temp_return_min" class="min_value ">18</div>
</div>
<div id="<?php echo $this->plugin_name;?>_current_value" class="div_value div_elements_layout">?</div>
<div class="footer-title">Temperatuur Retour</div>